[package]
name = "rcgen"
version = "0.12.1"
documentation = "https://docs.rs/rcgen"
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true
keywords.workspace = true

[[example]]
name = "rsa-irc"
required-features = ["pem"]

[[example]]
name = "rsa-irc-openssl"
required-features = ["pem"]

[[example]]
name = "sign-leaf-with-ca"
required-features = ["pem", "x509-parser"]

[dependencies]
aws-lc-rs = { version = "1.0.0", optional = true }
yasna = { version = "0.5.2", features = ["time", "std"] }
ring = { version = "0.17", optional = true }
pem = { workspace = true, optional = true }
time = { version = "0.3.6", default-features = false }
x509-parser = { version = "0.15", features = ["verify"], optional = true }
zeroize = { version = "1.2", optional = true }

[features]
default = ["pem", "ring"]
aws_lc_rs = ["dep:aws-lc-rs"]
ring = ["dep:ring"]

[package.metadata.docs.rs]
features = ["x509-parser"]

[package.metadata.cargo_check_external_types]
allowed_external_types = [
    "time::offset_date_time::OffsetDateTime",
    "zeroize::Zeroize"
]

[dev-dependencies]
openssl = "0.10"
x509-parser = { version = "0.15", features = ["verify"] }
rustls-webpki = { version = "0.101.0", features = ["std"] }
botan = { version = "0.10", features = ["vendored"] }
rand = "0.8"
rsa = "0.9"
ring = "0.17"
